# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Syn_SC
                                 A QGIS plugin
 Generate high-volume synthetic point data with user-defined continuity & smoothness
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-23
        copyright            : (C) 2025 by Anonymous Research Team
        email                : withheld@review.local
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Anonymous Research Team'
__date__ = '2025-06-23'
__copyright__ = '(C) 2025 by Anonymous Research Team'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Syn_SC class from file Syn_SC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .syn_sc import Syn_SCPlugin
    return Syn_SCPlugin()
